server:
  servlet:
    context-path: /homework


  port: 8881

spring:
#  jackson:
#    date-format: yyyy-MM-dd HH:mm:ss
#    time-zone: GMT+8



  datasource:
    # local server configuration(Mysql)
#    url: jdbc:mysql://cdb-fqh1b3fq.bj.tencentcdb.com:10104/RSS?characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
#    username: root
#    password: "root_RSS"
#    driver-class-name: com.mysql.cj.jdbc.Driver

    url: jdbc:mysql://localhost:3306/competitionsystem?serverTimezone=UTC&useSSL=false
    username: root
    password: "strawberryPi014"
    driver-class-name: com.mysql.cj.jdbc.Driver

    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 86400

  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.configuration.ImprovedNamingStrategy

    database-platform: org.hibernate.dialect.MySQL5Dialect

  thymeleaf:
    prefix: classpath:/templates/
    suffix: [.html|.jsp]
    mode: HTML
    encoding: UTF-8
    cache: false
    servlet:
      content-type: text/html